### ISSUE TITLE
Create CI / scanning practices

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/open-source-guidelines#13]
Example from 18F

- https://before-you-ship.18f.gov/security/scanning/

**Comment by IanLee1521** [comment]
Also: https://github.com/cfpb/open-source-checklist (thanks @afeld!)

**Comment by dinatale2** [comment]
CI options:
- [Travis CI](https://travis-ci.org/) (has a free option, integrated with GitHub)
- [Buildbot](https://buildbot.net/) (open source, free to use, integration with Amazon Web Services)
- [Jenkins](https://jenkins.io/)

Code Coverage:
- [codecov](https://codecov.io/)

Static Analysis:
- [Coverity](https://www.synopsys.com/software-integrity/resources/datasheets/coverity.html)

Patch Review/Management:
- [Gerrit](https://www.gerritcodereview.com/)

I'll edit this post when I think of other tools.

**Comment by IanLee1521** [comment]
@dinatale2 -- I think this might be a duplicate of #8

**Comment by dinatale2** [comment]
@IanLee1521 I think you're right. Shall we close this one?
